### ISSUE TITLE
Marke, Name und Preis fehlen noch auf den generierten Bildern

### ISSUE THREAD

**Issue by higgenseN** [epoyraz/GalaxusPlakatGenerator#10]
http://plakat-generator.westeurope.azurecontainer.io/generate?spruch=Hello&link=https%3A%2F%2Fwww.galaxus.ch%2Fde%2Fs1%2Fproduct%2Fsony-playstation-4-slim-500gb-de-fr-it-en-spielkonsole-5895212

Auf den generierten Bildern fehlen noch die jeweiligen Produktinformationen

**Comment by epoyraz** [comment]
erledigt
