### ISSUE TITLE
Text wird nicht bildgerecht formatiert bei zu langem Text

### ISSUE THREAD

**Issue by higgenseN** [epoyraz/GalaxusPlakatGenerator#6]
http://plakat-generator.westeurope.azurecontainer.io/generate?spruch=Wenn%20Text%20zu%20lang%20ist%20&link=https%3A%2F%2Fwww.galaxus.ch%2Fde%2Fs1%2Fproduct%2Fsony-playstation-4-slim-500gb-de-fr-it-en-spielkonsole-5895212

Hier als Beispiel
Der Text sollte Zeilenumbrüche und so weiter von selbst einfügen wenn die Gefahr besteht aus dem Bild herauszuragen

**Comment by epoyraz** [comment]
erledigt
