### ISSUE TITLE
Wenn das Bild zu groß ist, werden Teile abgeschnitten

### ISSUE THREAD

**Issue by higgenseN** [epoyraz/GalaxusPlakatGenerator#8]
http://plakat-generator.westeurope.azurecontainer.io/generate?spruch=Wenn%20Text%20zu%20lang%20ist%20&link=https%3A%2F%2Fwww.galaxus.ch%2Fde%2Fs2%2Fproduct%2Fcorona-extra-6-x-35-cl-bier-7155593

Hier als Beispiel, das draufzugenerierende Bild sollte je nach Größe richtig berechnet werden

**Comment by epoyraz** [comment]
ist erledigt
